{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.name }}-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.rbac.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
